---
- name: Set locale
  #when: "'UTF-8' not in lookup('env', 'LANG')"
  become: yes
  block:
  - ansible.builtin.apt:
      update_cache: yes
      name: locales
  - community.general.locale_gen: 
      name: en_US.UTF-8
  - ansible.builtin.shell: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

- name: Add universe repo
  become: yes
  block:
  - ansible.builtin.apt:
      update_cache: yes
      name: software-properties-common
  - ansible.builtin.shell: add-apt-repository universe
  - debug:
      msg: "{{ lookup('env', 'LANG') }}"

- name: Add ROS2 repo
  become: yes
  block:
  - ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
      keyring: /usr/share/keyrings/ros-archive-keyring.gpg
  - ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main
    
- name: Install ROS2 Foxy
  become: yes
  block:
  - ansible.builtin.apt:
      update_cache: yes
      upgrade: yes
  - ansible.builtin.apt:
      pkg:
      - ros-foxy-desktop
      - python3-argcomplete
