---
- name: Add Ubuntu Universe repo
  become: yes
  block:
  - name: Install software-properties-common
    ansible.builtin.apt:
      update_cache: yes
      name: software-properties-common
  - name: Add repo
    ansible.builtin.shell: add-apt-repository universe

- name: Add ROS2 repo
  become: yes
  block:
  - name: Add key
    ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
      keyring: /usr/share/keyrings/ros-archive-keyring.gpg
  - name: Add repo
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main

- name: Install ROS2 Foxy
  become: yes
  block:
  - name: Upgrade packages
    ansible.builtin.apt:
      update_cache: yes
      upgrade: yes
  - name: Install ROS2 packages
    ansible.builtin.apt:
      pkg:
      - ros-foxy-desktop
      - python3-argcomplete
